version: '3.8'

services:
  url-shortner-app:
    container_name: shortner_container
    restart: always
    build: .
    # uncomment for local django dev
    # volumes:
    #   - ./url_shortner:/apps
    ports:
      - 8000:8000
    networks:
      - internal
  url-shortner-frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    container_name: shortner_frontend
    restart: always
    ports:
      - 3000:3000
    # uncomment for react local dev
    # volumes:
    #   - ./frontend:/app
    networks:
      - internal
networks:
  internal:
    name: internal



